#!/command/with-contenv bash

echo "Starting unbound"

mkdir -p /var/log/unbound
touch /var/log/unbound/unbound.log
chmod 644 /var/log/unbound/unbound.log

NAME="unbound"
DESC="DNS server"
DAEMON="/usr/sbin/unbound"
PIDFILE="/run/unbound.pid"

test -x $DAEMON || exit 0

# Override this variable by editing or creating /etc/default/unbound.
DAEMON_OPTS=""

if [ -f /etc/default/unbound ]; then
    . /etc/default/unbound
fi

$DAEMON -d $DAEMON_OPTS
